version: '3'

services:
  organizr:
    restart: unless-stopped
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      # - RUN_OPTS=<run options here> #optional
    ports:
      - 9117:9117
    volumes:
      - ./config:/config
      - ./blackhole:/downloads