- name: create service root directory
  file:
    path: "{{ services_path.jackett.root }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    #mode: 0775
    #recurse: yes

- name: create service main directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '{{ services_path.jackett.root }}/config'


- name: Create links to media 
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: '{{ services_path.jackett.blackhole }}', dest: '{{ services_path.jackett.root }}/blackhole' }

- name: create env file
  include_role:
    name: docker_env
  vars:
    env_destination: '{{ services_path.jackett.root }}'    


- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: "{{ services_path.jackett.root }}/docker-compose.yml"
