music_library_path: /volume1/music/library
music_downloads_path: /volume1/music/downloads


music_cloud_user: main
music_cloud_group: users
music_cloud_path: /volume1/docker/services/music_cloud


beets_path: '{{ music_cloud_path }}/data/beets'
ampache_path: '{{ music_cloud_path }}/data/ampache'
