version: '3'

services:
  airsonic:
    #restart: unless-stopped
    image: linuxserver/airsonic:latest
    #image: airsonic/airsonic:latest
    container_name: airsonic
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "Europe/London"
      # CONTEXT_PATH=URL_BASE #optional
      # JAVA_OPTS=options #optional
    ports:
      - 4040:4040
    volumes:
      #- /volume1/docker/services/airsonic/config:/config
      #- /volume1/music/Music:/music
      #- /volume1/music/Playlists:/playlists
      #- /volume1/music/Podcasts:/podcasts
      - ./config:/config
      - /home/bigforcegun/music/library/Music:/music
      - /home/bigforcegun/music/library/Playlists:/playlists
      - /home/bigforcegun/music/library/Podcasts:/podcasts
