music_library_path: /volume1/music/library
music_downloads_path: /volume1/music/downloads

videos_library_path: /volume1/videos

music_cloud_user: main
music_cloud_group: users
music_cloud_path: /volume1/docker/services/music_cloud


beets_path: '{{ music_cloud_path }}/data/beets'
ampache_path: '{{ music_cloud_path }}/data/ampache'


jellyfin_service_path: /volume1/docker/services/jellyfin
jellyfin_user: main
jellyfin_group: users

video_library_path: /volume1/video


services_root: "/volume1/docker/services"
services_path:
    organizr: "{{ services_root }}/organizr"
    jackett:
        root: "{{ services_root }}/jackett"
        blackhole: "/volume1/data/downloads/jackett"




user:
    name: main
    group: users
    uid: 1026
    gid: 100

docker_env: true