- name: Create Main directory
  file:
    path: "{{ music_cloud_path }}"
    state: directory
    owner: "{{ music_cloud_user }}"
    group: "{{ music_cloud_group }}"
    #mode: 0775
    #recurse: yes

- name: Create Beets directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '{{ beets_path }}/config'

- name: Create Ampache directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '{{ ampache_path }}/config'
    - '{{ ampache_path }}/data'
    - '{{ ampache_path }}/metadata'

- name: Change config to Ampache www-data user
  file:
    state: directory
    path: '{{ ampache_path }}/config'
    mode: '0777' # temp hack  (need write custom docker container witout mysql and with good user mappings)    


- name: Fix metadata permissions
  file:
    state: directory
    path: '{{ ampache_path }}/metadata'
    mode: '0775' # temp hack  (need write custom docker container witout mysql and with good user mappings)  
     
# - name: Clone ampache docker repo
#   git:
#     repo: 'https://github.com/ampache/ampache-docker'
#     dest: '{{ ampache_path }}/docker'
    
# - name: Build fresh Ampache image
#   shell: "sudo /usr/local/bin/docker build -t ampache4_local_build ."
#   become_method: sudo
#   become_user: root
#   args: 
#     chdir: '{{ ampache_path }}/docker'
    
    
# - name: Build image and with build args
#   docker_image:
#     name: ampache4_local_build
#     build:
#       path: '{{ ampache_path }}/docker'
#     source: build

- name: Create links to directories
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  loop:
    - { src: '{{ music_library_path }}', dest: '{{ music_cloud_path }}/media' }
    - { src: '{{ music_downloads_path }}', dest: '{{ music_cloud_path }}/downloads' }   

- name: Copy Beets files
  copy:
    src: files/beets/config.yaml
    dest: "{{ beets_path }}/config/config.yaml"

- name: Copy Ampache files
  copy:
    src: files/ampache/ampache.cfg.php
    dest: "{{ ampache_path }}/config/ampache.cfg.php"
  
- name: Copy compose file
  copy:
    src: files/docker-compose.yml
    dest: "{{ music_cloud_path }}/docker-compose.yml"

- name: Copy Ampache fix entrypoint
  copy:
    src: files/ampache/entrypoint.sh
    dest: "{{ music_cloud_path }}/ampache-entrypoint.sh"
    mode: a+x


# - name: Start Prometheus service
#   docker_service:
#     project_src: "{{ prometheus_home }}"
        